insert into licenses (spdx, name, created_at, updated_at) values ('AFL-1.2', 'Academic Free License v1.2', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('AFL-2.0', 'Academic Free License v2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('AFL-2.1', 'Academic Free License v2.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('AFL-3.0', 'Academic Free License v3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('APL-1.0', 'Adaptive Public License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ANTLR-PD', 'ANTLR Software Rights Notice', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Apache-1.0', 'Apache License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Apache-1.1', 'Apache License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Apache-2.0', 'Apache License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('APSL-1.0', 'Apple Public Source License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('APSL-1.1', 'Apple Public Source License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('APSL-1.2', 'Apple Public Source License 1.2', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('APSL-2.0', 'Apple Public Source License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Artistic-1.0', 'Artistic License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Artistic-2.0', 'Artistic License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('AAL', 'Attribution Assurance License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('BSL-1.0', 'Boost Software License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('BSD-2-Clause', 'BSD 2-clause "Simplified" or "FreeBSD" License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('BSD-3-Clause', 'BSD 3-clause "New" or "Revised" License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('BSD-4-Clause', 'BSD 4-clause "Original" or "Old" License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CECILL-1.0', 'CeCILL Free Software License Agreement v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CECILL-2.0', 'CeCILL Free Software License Agreement v2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CECILL-B', 'CeCILL-B Free Software License Agreement', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CECILL-C', 'CeCILL-C Free Software License Agreement', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ClArtistic', 'Clarified Artistic License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CDDL-1.0', 'Common Development and Distribution License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CPAL-1.0', 'Common Public Attribution License 1.0 ', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CPL-1.0', 'Common Public License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CATOSL-1.1', 'Computer Associates Trusted Open Source License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-1.0', 'Creative Commons Attribution 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-2.0', 'Creative Commons Attribution 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-2.5', 'Creative Commons Attribution 2.5', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-3.0', 'Creative Commons Attribution 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-ND-1.0', 'Creative Commons Attribution No Derivatives 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-ND-2.0', 'Creative Commons Attribution No Derivatives 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-ND-2.5', 'Creative Commons Attribution No Derivatives 2.5', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-ND-3.0', 'Creative Commons Attribution No Derivatives 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-1.0', 'Creative Commons Attribution Non Commercial 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-2.0', 'Creative Commons Attribution Non Commercial 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-2.5', 'Creative Commons Attribution Non Commercial 2.5', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-3.0', 'Creative Commons Attribution Non Commercial 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-ND-1.0', 'Creative Commons Attribution Non Commercial No Derivatives 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-ND-2.0', 'Creative Commons Attribution Non Commercial No Derivatives 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-ND-2.5', 'Creative Commons Attribution Non Commercial No Derivatives 2.5', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-ND-3.0', 'Creative Commons Attribution Non Commercial No Derivatives 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-SA-1.0', 'Creative Commons Attribution Non Commercial Share Alike 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-SA-2.0', 'Creative Commons Attribution Non Commercial Share Alike 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-SA-2.5', 'Creative Commons Attribution Non Commercial Share Alike 2.5', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-NC-SA-3.0', 'Creative Commons Attribution Non Commercial Share Alike 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-SA-1.0', 'Creative Commons Attribution Share Alike 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-SA-2.0', 'Creative Commons Attribution Share Alike 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-SA-2.5', 'Creative Commons Attribution Share Alike 2.5', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC-BY-SA-3.0', 'Creative Commons Attribution Share Alike 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CC0-1.0', 'Creative Commons Zero v1.0 Universal', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('CUA-OPL-1.0', 'CUA Office Public License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('EPL-1.0', 'Eclipse Public License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('eCos-2.0', 'eCos license version 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ECL-1.0', 'Educational Community License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ECL-2.0', 'Educational Community License v2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('EFL-1.0', 'Eiffel Forum License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('EFL-2.0', 'Eiffel Forum License v2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Entessa', 'Entessa Public License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ErlPL-1.1', 'Erlang Public License v1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('EUDatagrid', 'EU DataGrid Software License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('EUPL-1.0', 'European Union Public License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('EUPL-1.1', 'European Union Public License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Fair', 'Fair License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Frameworx-1.0', 'Frameworx Open License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('AGPL-3.0', 'GNU Affero General Public License v3', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GFDL-1.2', 'GNU Free Documentation License v1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GFDL-1.2', 'GNU Free Documentation License v1.2', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GFDL-1.3', 'GNU Free Documentation License v1.3', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-1.0', 'GNU General Public License v1.0 only', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-1.0+', 'GNU General Public License v1.0 or later', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2.0', 'GNU General Public License v2.0 only', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2.0+', 'GNU General Public License v2.0 or later', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2.0-with-autoconf-exception', 'GNU General Public License v2.0 w/Autoconf exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2-with-bison-exception', 'GNU General Public License v2.0 w/Bison exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2.0-with-classpath-exception', 'GNU General Public License v2.0 w/Classpath exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2.0-with-font-exception', 'GNU General Public License v2.0 w/Font exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-2.0-with-GCC-exception', 'GNU General Public License v2.0 w/GCC Runtime Library exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-3.0', 'GNU General Public License v3.0 only', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-3.0+', 'GNU General Public License v3.0 or later', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-3.0-with-autoconf-exception', 'GNU General Public License v3.0 w/Autoconf exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('GPL-3.0-with-GCC-exception', 'GNU General Public License v3.0 w/GCC Runtime Library exception', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LGPL-2.1', 'GNU Lesser General Public License v2.1 only', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LGPL-2.1+', 'GNU Lesser General Public License v2.1or later', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LGPL-3.0', 'GNU Lesser General Public License v3.0 only', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LGPL-3.0+', 'GNU Lesser General Public License v3.0 or later', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LGPL-2.0', 'GNU Library General Public License v2 only', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LGPL-2.0+', 'GNU Library General Public License v2 or later', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('gSOAP-1.3b', 'gSOAP Public License v1.b', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('HPND', 'Historic Permission Notice and Disclaimer', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('IPL-1.0', 'IBM Public License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('IPA', 'IPA Font License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ISC', 'ISC License (Bind, DHCP Server)', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LPPL-1.0', 'LaTeX Project Public License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LPPL-1.1', 'LaTeX Project Public License v1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LPPL-1.2', 'LaTeX Project Public License v1.2', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LPPL-1.3c', 'LaTeX Project Public License v1.3c', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Libpng', 'libpng License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('LPL-1.02', 'Lucent Public License v1.02 (Plan9)', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('MS-PL', 'Microsoft Public License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('MS-RL', 'Microsoft Reciprocal License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('MirOS', 'MirOS Licence', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('MIT', 'MIT license (also X11)', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Motosoto', 'Motosoto License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('MPL-1.0', 'Mozilla Public License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('MPL-1.1', 'Mozilla Public License 1.1 ', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Multics', 'Multics License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('NASA-1.3', 'NASA Open Source Agreement 1.3', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Nauman', 'Naumen Public License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('NGPL', 'Nethack General Public License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Nokia', 'Nokia Open Source License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('NPOSL-3.0', 'Non-Profit Open Software License 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('NTP', 'NTP License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OCLC-2.0', 'OCLC Research Public License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ODbL-1.0', 'ODC Open Database License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OGTSL', 'Open Group Test Suite License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OSL-1.0', 'Open Software License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OSL-2.0', 'Open Software License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OSL-3.0', 'Open Software License 3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OLDAP-2.8', 'OpenLDAP Public License v2.8', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OpenSSL', 'OpenSSL License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('PHP-3.0', 'PHP License v3.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('PostgreSQL', 'PostgreSQL License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Python-2.0', 'Python Software Foundation License v2', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('QPL-1.0', 'Q Public License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('RPSL-1.0', 'RealNetworks Public Source License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('RPL-1.5', 'Reciprocal Public License 1.5 ', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('RHeCos-1.1', 'Red Hat eCos Public License v1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('RSCPL', 'Ricoh Source Code Public License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Ruby', 'Ruby License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('SAX-PD', 'Sax Public Domain Notice', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('OFL-1.1', 'SIL Open Font License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Simple-2.0', 'Simple Public License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Sleepycat', 'Sleepycat License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('SugarCRM-1.1.3', 'SugarCRM Public License v1.1.3', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('SPL-1.0', 'Sun Public License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Watcom-1.0', 'Sybase Open Watcom Public License 1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('NCSA', 'University of Illinois/NCSA Open Source License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('VSL-1.0', 'Vovida Software License v1.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('W3C', 'W3C Software and Notice License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('WXwindows', 'wxWindows Library License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Xnet', 'X.Net License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('XFree86-1.1', 'XFree86 License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('YPL-1.1', 'Yahoo! Public License v1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Zimbra-1.3', 'Zimbra Publice License v1.3', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('Zlib', 'zlib License', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ZPL-1.1', 'Zope Public License 1.1', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ZPL-2.0', 'Zope Public License 2.0', now(), now());
insert into licenses (spdx, name, created_at, updated_at) values ('ZPL-2.1', 'Zope Public License 2.1', now(), now());